# Generated by Django 5.2.17 on 2026-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('hilang', 'Hilang'), ('ditemukan', 'Ditemukan')], max_length=10)),
            ],
        ),
    ]
